#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# Set the python io encoding to UTF-8 by default if not set.
if [ -z ${PYTHONIOENCODING+x} ]; then export PYTHONIOENCODING=utf8; fi

create_export_script() {
  mkdir -p scripts
  cat << EOF >> ./scripts/create_ddls.sql
SET SERVEROUT ON SIZE 1000000
SET LONG 2000000
SET LONGCHUNKSIZE 2000000
SET LINESIZE 32676
SET TERMOUT OFF
SET HEADING OFF
SET PAGESIZE 0
SET TRIMSPOOL ON
SET VERIFY OFF
SET FEEDBACK OFF
SET SHOWMODE OFF

execute dbms_metadata.set_transform_param (dbms_metadata.session_transform,'CONSTRAINTS_AS_ALTER', false);
execute dbms_metadata.set_transform_param (DBMS_METADATA.session_transform,'SQLTERMINATOR', true);
execute dbms_metadata.set_transform_param (DBMS_METADATA.session_transform,'PRETTY',true);
--
spool object_extracts/DDL/DDL_Tables.sql

SELECT '/* <sc-table> ' || owner || '.' || object_name || ' </sc-table> */', DBMS_METADATA.get_ddl(object_type, object_name, owner) 
FROM DBA_OBJECTS 
WHERE object_Type IN ('TABLE')
AND status = 'VALID' 
AND owner &1 &2
AND owner NOT &3 &4 
AND owner NOT IN ('EXFSYS','SYSMAN','DMSYS','ANONYMOUS','APPQOSSYS','AUDSYS','CTXSYS','DBSFWUSER','DBSNMP','DVF','DVSYS','GGSYS','GSMADMIN_INTERNAL','LBACSYS','MDDATA','MDSYS','OJVMSYS','OLAPSYS','OUTLN','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','REMOTE_SCHEDULER_AGENT','SYS','SYSTEM','WMSYS','XDB')
AND owner NOT LIKE 'DBA%'
AND owner NOT LIKE 'APEX%'
AND (owner, object_name) not in (select owner, table_name from dba_nested_tables)
AND (owner, object_name) not in (select owner, table_name from dba_tables where iot_type = 'IOT_OVERFLOW');
spool off

--
spool object_extracts/DDL/DDL_Views.sql

SELECT '/* <sc-view> ' || owner || '.' || object_name || ' </sc-view> */', DBMS_METADATA.get_ddl(object_type, object_name, owner) 
FROM DBA_OBJECTS 
WHERE object_Type IN ('VIEW')
AND status = 'VALID' 
AND owner &1 &2
AND owner NOT &3 &4
AND owner NOT IN ('EXFSYS','SYSMAN','DMSYS','ANONYMOUS','APPQOSSYS','AUDSYS','CTXSYS','DBSFWUSER','DBSNMP','DVF','DVSYS','GGSYS','GSMADMIN_INTERNAL','IX','LBACSYS','MDDATA','MDSYS','OJVMSYS','OLAPSYS','OUTLN','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','REMOTE_SCHEDULER_AGENT','SYS','SYSTEM','WMSYS','XDB')
AND owner NOT LIKE 'DBA%'
AND owner NOT LIKE 'APEX%'
AND owner NOT LIKE 'ORDS%'
AND owner NOT LIKE 'XDB%'
AND owner NOT LIKE 'XFILES%';

spool off

--

spool object_extracts/DDL/DDL_Functions.sql

SELECT '/* <sc-function> ' || owner || '.' || object_name || ' </sc-function> */', DBMS_METADATA.get_ddl(object_type, object_name, owner) 
FROM DBA_OBJECTS 
WHERE object_Type IN ('FUNCTION')
AND status = 'VALID' 
AND owner &1 &2
AND owner NOT &3 &4
AND owner NOT IN ('EXFSYS','SYSMAN','DMSYS','ANONYMOUS','APPQOSSYS','AUDSYS','CTXSYS','DBSFWUSER','DBSNMP','DVF','DVSYS','GGSYS','GSMADMIN_INTERNAL','LBACSYS','MDDATA','MDSYS','OJVMSYS','OLAPSYS','OUTLN','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','REMOTE_SCHEDULER_AGENT','SYS','SYSTEM','WMSYS','XDB')
AND owner NOT LIKE 'DBA%'
AND owner NOT LIKE 'APEX%';

spool off

--
spool object_extracts/DDL/DDL_Procedures.sql

SELECT '/* <sc-procedure> ' || owner || '.' || object_name || ' </sc-procedure> */', DBMS_METADATA.get_ddl(object_type, object_name, owner) 
FROM DBA_OBJECTS 
WHERE object_Type IN ('PROCEDURE') 
AND status = 'VALID'
AND owner &1 &2
AND owner NOT &3 &4
AND owner NOT IN ('EXFSYS','SYSMAN','DMSYS','ANONYMOUS','APPQOSSYS','AUDSYS','CTXSYS','DBSFWUSER','DBSNMP','DVF','DVSYS','GGSYS','GSMADMIN_INTERNAL','LBACSYS','MDDATA','MDSYS','OJVMSYS','OLAPSYS','OUTLN','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','REMOTE_SCHEDULER_AGENT','SYS','SYSTEM','WMSYS','XDB')
AND owner NOT LIKE 'DBA%'
AND owner NOT LIKE 'APEX%'
AND owner NOT LIKE 'ORDS%';


spool off

--

spool object_extracts/DDL/DDL_Packages.sql

SELECT '/* <sc-package> ' || owner || '.' || object_name || ' </sc-package> */', DBMS_METADATA.get_ddl(object_type, object_name, owner) 
FROM DBA_OBJECTS 
WHERE object_Type IN ('PACKAGE') 
AND status = 'VALID'
AND owner &1 &2
AND owner NOT &3 &4
AND owner NOT IN ('EXFSYS','SYSMAN','DMSYS','ANONYMOUS','APPQOSSYS','AUDSYS','CTXSYS','DBSFWUSER','DBSNMP','DVF','DVSYS','GGSYS','GSMADMIN_INTERNAL','LBACSYS','MDDATA','MDSYS','OJVMSYS','OLAPSYS','OUTLN','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','REMOTE_SCHEDULER_AGENT','SYS','SYSTEM','WMSYS','XDB')
AND owner NOT LIKE 'DBA%'
AND owner NOT LIKE 'APEX%'
AND owner NOT LIKE 'ORDS%'
AND owner NOT LIKE 'XDB%'
AND owner NOT LIKE 'XFILES%';

spool off

--

spool object_extracts/DDL/DDL_Synonyms.sql

SELECT '/* <sc-synonym> ' || owner || '.' || object_name || ' </sc-synonym> */', DBMS_METADATA.get_ddl(object_type, object_name, owner) 
FROM DBA_OBJECTS 
WHERE object_Type IN ('SYNONYM')
AND status = 'VALID' 
AND owner &1 &2
AND owner NOT &3 &4
AND owner NOT IN ('EXFSYS','SYSMAN','DMSYS','ANONYMOUS','APPQOSSYS','AUDSYS','CTXSYS','DBSFWUSER','DBSNMP','DVF','DVSYS','GGSYS','GSMADMIN_INTERNAL','LBACSYS','MDDATA','MDSYS','OJVMSYS','OLAPSYS','OUTLN','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','REMOTE_SCHEDULER_AGENT','SYS','SYSTEM','WMSYS','XDB')
AND owner NOT LIKE 'DBA%'
AND owner NOT LIKE 'APEX%'
AND owner NOT LIKE 'PUBLIC%'
AND owner NOT LIKE 'SI_INFORMTN_SCHEMA%'
AND owner NOT LIKE 'FLOWS_FILES%'
AND owner NOT LIKE 'ORDS%'
AND owner NOT LIKE 'XDB%'
AND owner NOT LIKE 'XFILES%'
;

spool off

--

spool object_extracts/DDL/DDL_Types.sql

SELECT '/* <sc-type> ' || owner || '.' || object_name || ' </sc-type> */', DBMS_METADATA.get_ddl(object_type, object_name, owner) 
FROM DBA_OBJECTS 
WHERE object_Type IN ('TYPE') 
AND status = 'VALID'
AND owner &1 &2
AND owner NOT &3 &4
AND owner NOT IN ('EXFSYS','SYSMAN','DMSYS','ANONYMOUS','APPQOSSYS','AUDSYS','CTXSYS','DBSFWUSER','DBSNMP','DVF','DVSYS','GGSYS','GSMADMIN_INTERNAL','IX','LBACSYS','MDDATA','MDSYS','OJVMSYS','OLAPSYS','OUTLN','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','PM','REMOTE_SCHEDULER_AGENT','SYS','SYSTEM','WMSYS','XDB')
AND owner NOT LIKE 'DBA%'
AND owner NOT LIKE 'APEX%'
AND owner NOT LIKE 'ORDS%'
AND owner NOT LIKE 'XFILES%'
AND owner NOT LIKE 'XDB%'
AND object_name not like 'SYS_%';

spool off

--

spool object_extracts/DDL/DDL_Indexes.sql

SELECT '/* <sc-index> ' || owner || '.' || object_name || ' </sc-index> */', DBMS_METADATA.get_ddl(object_type, object_name, owner) 
FROM DBA_OBJECTS 
WHERE object_Type IN ('INDEX')
AND status = 'VALID' 
AND owner &1 &2
AND owner NOT &3 &4
AND owner NOT IN ('EXFSYS','SYSMAN','DMSYS','ANONYMOUS','APPQOSSYS','AUDSYS','CTXSYS','DBSFWUSER','DBSNMP','DBJSON','DVF','DVSYS','GGSYS','GSMADMIN_INTERNAL','IX','LBACSYS','MDDATA','MDSYS','OJVMSYS','OLAPSYS','OUTLN','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','PM','REMOTE_SCHEDULER_AGENT','SYS','SYSTEM','WMSYS','XDB')
AND owner NOT LIKE 'DBA%'
AND owner NOT LIKE 'APEX%'
AND owner NOT LIKE 'FLOWS_FILES%'
AND owner NOT LIKE 'ORDS%'
AND owner NOT LIKE 'XDB%'
AND owner NOT LIKE 'XFILES%';

spool off

--

spool object_extracts/DDL/DDL_Triggers.sql

SELECT '/* <sc-trigger> ' || owner || '.' || object_name || ' </sc-trigger> */', DBMS_METADATA.get_ddl(object_type, object_name, owner) 
FROM DBA_OBJECTS 
WHERE object_Type IN ('TRIGGER')
AND status = 'VALID' 
AND owner &1 &2
AND owner NOT &3 &4
AND owner NOT IN ('EXFSYS','SYSMAN','DMSYS','ANONYMOUS','APPQOSSYS','AUDSYS','CTXSYS','DBSFWUSER','DBSNMP','DVF','DVSYS','GGSYS','GSMADMIN_INTERNAL','LBACSYS','MDDATA','MDSYS','OJVMSYS','OLAPSYS','OUTLN','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','REMOTE_SCHEDULER_AGENT','SYS','SYSTEM','WMSYS','XDB')
AND owner NOT LIKE 'DBA%'
AND owner NOT LIKE 'APEX%'
AND owner NOT LIKE 'FLOWS_FILES%'
AND owner NOT LIKE 'ORDS%'
AND owner NOT LIKE 'XDB%'
AND owner NOT LIKE 'XFILES%';

spool off

--

spool object_extracts/DDL/DDL_Sequences.sql

SELECT '/* <sc-sequence> ' || owner || '.' || object_name || ' </sc-sequence> */', DBMS_METADATA.get_ddl(object_type, object_name, owner) 
FROM DBA_OBJECTS 
WHERE object_Type IN ('SEQUENCE')
AND status = 'VALID' 
AND owner &1 &2
AND owner NOT &3 &4
AND owner NOT IN ('EXFSYS','SYSMAN','DMSYS','ANONYMOUS','APPQOSSYS','AUDSYS','CTXSYS','DBSFWUSER','DBSNMP','DVF','DVSYS','GGSYS','GSMADMIN_INTERNAL','IX','LBACSYS','MDDATA','MDSYS','OJVMSYS','OLAPSYS','OUTLN','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','REMOTE_SCHEDULER_AGENT','SYS','SYSTEM','WMSYS','XDB')
AND owner NOT LIKE 'DBA%'
AND owner NOT LIKE 'APEX%'
AND owner NOT LIKE 'ORDS%'
AND owner NOT LIKE 'XDB%';

spool off

--

spool object_extracts/DDL/DDL_DBlink.sql

SELECT 
'/* <sc-dblink> ' || owner || '.' || db_link || ' </sc-dblink> */', DBMS_METADATA.get_ddl('DB_LINK', db_link, owner) 
FROM dba_db_links 
WHERE 1=1 -- VALID = 'YES'
AND owner &1 &2
AND owner NOT &3 &4
AND owner NOT IN ('EXFSYS','SYSMAN','DMSYS','ANONYMOUS','APPQOSSYS','AUDSYS','CTXSYS','DBSFWUSER','DBSNMP','DVF','DVSYS','GGSYS','GSMADMIN_INTERNAL','LBACSYS','MDDATA','MDSYS','OJVMSYS','OLAPSYS','OUTLN','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','REMOTE_SCHEDULER_AGENT','SYS','SYSTEM','WMSYS','XDB')
AND owner NOT LIKE 'DBA%'
AND owner NOT LIKE 'APEX%';

spool off

--

spool object_extracts/DDL/DDL_QUEUE_TABLES.sql

SELECT '/* <sc-queue_table> ' || owner || '.' || queue_table || ' </sc-queue_table> */', DBMS_METADATA.get_ddl('TABLE', queue_table, owner) 
FROM DBA_QUEUE_TABLES 
WHERE 
owner &1 &2
AND owner NOT &3 &4 
AND owner NOT IN ('EXFSYS','SYSMAN','DMSYS','ANONYMOUS','APPQOSSYS','AUDSYS','CTXSYS','DBSFWUSER','DBSNMP','DVF','DVSYS','GGSYS','GSMADMIN_INTERNAL','IX','LBACSYS','MDDATA','MDSYS','OJVMSYS','OLAPSYS','OUTLN','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','REMOTE_SCHEDULER_AGENT','SYS','SYSTEM','WMSYS','XDB')
AND owner NOT LIKE 'DBA%'
AND owner NOT LIKE 'APEX%'
AND owner NOT LIKE 'XDB%'
AND owner NOT LIKE 'XFILES%'
AND (owner, queue_table) not in (select owner, table_name from dba_nested_tables)
AND (owner, queue_table) not in (select owner, table_name from dba_tables where iot_type = 'IOT_OVERFLOW');

spool off

--

spool object_extracts/DDL/DDL_OLAP_CUBES.sql

SELECT '/* <sc-olap_cube> ' || owner || '.' || cube_name || ' </sc-olap_cube> */', DBMS_METADATA.get_ddl('CUBE', cube_name, owner) 
FROM DBA_CUBES 
WHERE 
owner &1 &2
AND owner NOT &3 &4 
AND owner NOT IN ('EXFSYS','SYSMAN','DMSYS','ANONYMOUS','APPQOSSYS','AUDSYS','CTXSYS','DBSFWUSER','DBSNMP','DVF','DVSYS','GGSYS','GSMADMIN_INTERNAL','LBACSYS','MDDATA','MDSYS','OJVMSYS','OLAPSYS','OUTLN','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','REMOTE_SCHEDULER_AGENT','SYS','SYSTEM','WMSYS','XDB')
AND owner NOT LIKE 'DBA%'
AND owner NOT LIKE 'APEX%';

spool off

--

spool object_extracts/DDL/DDL_MATERIALIZED_VIEWS.sql

SELECT '/* <sc-materialized_view> ' || owner || '.' || mview_name || ' </sc-materialized_view> */', DBMS_METADATA.get_ddl('MATERIALIZED_VIEW', mview_name, owner) 
FROM DBA_MVIEWS 
WHERE 
owner &1 &2
AND owner NOT &3 &4 
AND owner NOT IN ('EXFSYS','SYSMAN','DMSYS','ANONYMOUS','APPQOSSYS','AUDSYS','CTXSYS','DBSFWUSER','DBSNMP','DVF','DVSYS','GGSYS','GSMADMIN_INTERNAL','LBACSYS','MDDATA','MDSYS','OJVMSYS','OLAPSYS','OUTLN','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','REMOTE_SCHEDULER_AGENT','SYS','SYSTEM','WMSYS','XDB')
AND owner NOT LIKE 'DBA%'
AND owner NOT LIKE 'APEX%';

spool off

--

spool object_extracts/DDL/DDL_QUEUES.sql

SELECT '/* <sc-queue> ' || owner || '.' || name || ' </sc-queue> */' 
FROM DBA_QUEUES 
WHERE 
owner &1 &2
AND owner NOT &3 &4 
AND owner NOT IN ('EXFSYS','SYSMAN','DMSYS','ANONYMOUS','APPQOSSYS','AUDSYS','CTXSYS','DBSFWUSER','DBSNMP','DVF','DVSYS','GGSYS','GSMADMIN_INTERNAL','IX','LBACSYS','MDDATA','MDSYS','OJVMSYS','OLAPSYS','OUTLN','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','REMOTE_SCHEDULER_AGENT','SYS','SYSTEM','WMSYS','XDB')
AND owner NOT LIKE 'DBA%'
AND owner NOT LIKE 'APEX%'
AND owner NOT LIKE 'XDB%'
AND owner NOT LIKE 'XFILES%';

spool off

--

spool object_extracts/DDL/DDL_ANALYTIC_VIEWS.sql

SELECT '/* <sc-analytic_view> ' || owner || '.' || analytic_view_name || ' </sc-analytic_view> */', DBMS_METADATA.get_ddl('ANALYTIC_VIEW', analytic_view_name, owner)
FROM DBA_ANALYTIC_VIEWS 
WHERE 
owner &1 &2
AND owner NOT &3 &4 
AND owner NOT IN ('EXFSYS','SYSMAN','DMSYS','ANONYMOUS','APPQOSSYS','AUDSYS','CTXSYS','DBSFWUSER','DBSNMP','DVF','DVSYS','GGSYS','GSMADMIN_INTERNAL','LBACSYS','MDDATA','MDSYS','OJVMSYS','OLAPSYS','OUTLN','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','REMOTE_SCHEDULER_AGENT','SYS','SYSTEM','WMSYS','XDB')
AND owner NOT LIKE 'DBA%'
AND owner NOT LIKE 'APEX%';

spool off

--

spool object_extracts/DDL/DDL_OPERATORS.sql

SELECT '/* <sc-operator> ' || owner || '.' || operator_name || ' </sc-analytic_view> */', DBMS_METADATA.get_ddl('OPERATOR', operator_name, owner)
FROM DBA_OPERATORS 
WHERE 
owner &1 &2
AND owner NOT &3 &4
AND owner NOT IN ('EXFSYS','SYSMAN','DMSYS','ANONYMOUS','APPQOSSYS','AUDSYS','CTXSYS','DBSFWUSER','DBSNMP','DVF','DVSYS','GGSYS','GSMADMIN_INTERNAL','LBACSYS','MDDATA','MDSYS','OJVMSYS','OLAPSYS','OUTLN','ORACLE_OCM','ORDDATA','ORDPLUGINS','ORDSYS','REMOTE_SCHEDULER_AGENT','SYS','SYSTEM','WMSYS','XDB')
AND owner NOT LIKE 'DBA%'
AND owner NOT LIKE 'APEX%';

spool off

dbms_metadata.set_transform_param (dbms_metadata.session_transform, 'DEFAULT');

quit


EOF
}

echo "sc-oracle-export"

echo "This script will install the Oracle SQLCL tool and JDK to enable connection to your database"
echo "and the run "

install_tools() {
  mkdir -p tools

  echo "Installing Open JDK 11"
  JAVA_JDK=openjdk-11.0.2
  pushd .
  mkdir -p ./tools/java
  cd ./tools/java
  curl -LO https://corretto.aws/downloads/latest/amazon-corretto-11-x64-linux-jdk.tar.gz
  tar zxvf amazon-corretto-11-x64-linux-jdk.tar.gz
  rm -rf *.gz
  mv amazon-corretto* jdk11
  popd

  export JAVA_HOME=./tools/java/jdk11
  export PATH=$JAVA_HOME/bin:$PATH

  echo "Installing Oracle SQLCL"
  cd ./tools
  curl -O https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip
  unzip -o sqlcl-latest.zip
  chmod 755 ./sqlcl/bin/sql
  cd ..

  unset ORACLE_HOME
}

POSITIONAL=()
while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -h|--help)
      HELP="TRUE"
      shift # past argument
      ;;
    -H|--host)
      HOST="@$2"
      shift # past argument
      shift # past value
      ;;      
    -S|--service)
      SERVICE="@$2"
      shift # past argument
      shift # past value
      ;;
    -U|--user)
      USER="$2"
      shift # past argument
      shift # past value
      ;;
    -P|--password)
      PASSWORD="$2"
      shift # past argument
      shift # past value
      ;;
    --as-sysdba)
      SYSDBA="AS SYSDBA"
      shift # past argument
      ;;
    *)    # unknown option
      POSITIONAL+=("$1") # save it in an array for later
      shift # past argument
      ;;
  esac
done

if [ "$HELP" = "TRUE" ];
then
    echo "    usage: sc-oracle-export [-h]  [-U|--user USER] [-P|--password PASSWORD] [-C|--connect connect] [--as-sysdba]"
    echo ""
    echo "    Mobilize.NET Oracle Code Export ToolsVersion X.X.X"
    echo ""
    echo "    optional arguments:"
    echo "    -h , --help       Show this help message and exit"
    echo "    -S , --service    Service name. For example ORCL"
    echo "    -H , --host       Host"
    echo "    -U , --user       Login ID for server"
    echo "    -P , --password   The password for the given user."
    echo "    --as-sysdba       Connect as sysdba"
    exit 1
fi


echo "Install tools to connect to Oracle (yes/no/cancel)"
read answer

case $answer in
  y | Y | yes | YES ) answer="y";;
  n | N | no | NO ) answer="n";;
  *) exit 1;;
esac

if [ "$answer" = "y" ];
then
  install_tools
fi

create_export_script

./tools/sqlcl/bin/sql $USER/$PASSWORD@$HOST/$SERVICE $SYSDBA ./scripts/create_ddls.sql

echo "The script ./scripts/create_ddls.sql can be run to export your Oracle DDLs"