snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f address.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f addresstype.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f billofmaterials.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f businessentity.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f businessentityaddress.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f businessentitycontact.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f contacttype.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f countryregion.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f countryregioncurrency.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f creditcard.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f culture.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f currency.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f currencyrate.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f customer.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f databaselog.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f document.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f emailaddress.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f employee.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f employeedepartmenthistory.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f employeepayhistory.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f errorlog.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f illustration.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f jobcandidate.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f password.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f person.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f personcreditcard.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f personphone.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f phonenumbertype.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f product.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f productcategory.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f productcosthistory.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f productdescription.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f productdocument.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f productinventory.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f productlistpricehistory.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f productmodel.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f productmodelillustration.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f productmodelproductdescriptionculture.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f productphoto.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f productproductphoto.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f productreview.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f productsubcategory.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f productvendor.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f purchaseorderdetail.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f purchaseorderheader.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f salesorderdetail.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f salesorderheader.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f salesorderheadersalesreason.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f salesperson.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f salespersonquotahistory.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f salesreason.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f salestaxrate.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f salesterritory.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f salesterritoryhistory.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f schemas.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f shipmethod.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f shoppingcartitem.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f specialoffer.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f specialofferproduct.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f stateprovince.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f store.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f transactionhistory.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f transactionhistoryarchive.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f unitmeasure.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f vendor.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f workorder.sql
snowsql -a aws_cas2 -u acalvo_mobilize -r REDSHIFT_ROLE -w REDSHIFT_WH -d REDSHIFT -f workorderrouting.sql
