#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# Set the python io encoding to UTF-8 by default if not set.
if [ -z ${PYTHONIOENCODING+x} ]; then export PYTHONIOENCODING=utf8; fi

export PYTHONPATH="${DIR}:${PYTHONPATH}"
unameOut="$(uname -s)"
case "${unameOut}" in
    Darwin*)    MAC="TRUE";;
    Linux*)     LINUX="TRUE";;
    LINUX*)     LINUX="TRUE";;
    *)          OTHER="TRUE"
esac

POSITIONAL=()
while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
    -h|--help)
      HELP="TRUE"
      shift # past argument
      ;;
    -C|--connection-string)
      CONNSTR="$2"
      shift # past argument
      shift # past value
      ;;
    -S|--server)
      SERVER="$2"
      shift # past argument
      shift # past value
      ;;
    -U|--user)
      USER="$2"
      shift # past argument
      shift # past value
      ;;
    -P|--password)
      PASSWORD="$2"
      shift # past argument
      shift # past value
      ;;
    -D|--database)
      DATABASE="$2"
      shift # past argument
      shift # past value
      ;;
    *)    # unknown option
      POSITIONAL+=("$1") # save it in an array for later
      shift # past argument
      ;;
  esac
done



if [ "$HELP" = "TRUE" ];
then
    echo "    usage: sc-sqlserver-export [-h] [--connection-string CONNSTR] [-D|--database database] [-S|--server SERVER] [-U|--user USER] [-P|--password PASSWORD]"
    echo ""
    echo "    Mobilize.NET SQLServer Code Export ToolsVersion X.X.X"
    echo ""
    echo "    optional arguments:"
    echo "    -h, --help        show this help message and exit"
    echo "    -C , --connection-string"
    echo "                      DB connection string"
    echo "    -S , --server     Server address or name"
    echo "    -D , --database   Database name"
    echo "    -U , --user       Login ID for server"
    echo "    -P , --password   The password for the given user."
fi

if [[ -z "$CONNSTR" && -z "$SERVER" ]];
then
  echo "Please specify connection information using --connection-string or --server and/or --database --user."
  echo ""
  echo "usage: sc-sqlserver-export [-h] [--connection-string CONNSTR] [-D|--database database] [-S|--server SERVER] [-U|--user USER] [-P|--password PASSWORD]"
    
  exit 1
fi

if [ ! -z "$CONNSTR" ];
then
    mkdir -p ./output/DDL
    mssql-scripter --connection-string  --file-per-object -f ./output/DDL
fi

if [ ! -z "$SERVER" ];
then
    echo "SERVER  : $SERVER"
    echo "DATABASE: $DATABASE"
    echo "USER    : $USER"
    mkdir -p ./output/DDL
    mssql-scripter -S $SERVER -U $USER -P $PASSWORD --file-per-object -f ./output/DDL
fi