CREATE VIEW EMPLOYEE_JOB_DURATION_COMPARISONS
AS
LOCKING ROW FOR ACCESS
    SELECT 'OVERLAP' FUNC, FIRST_NAME, LAST_NAME
        FROM EMPLOYEE_JOB_PERIODS
        WHERE JOB_DURATION OVERLAPS PERIOD(DATE '2009-01-01', DATE '2010-09-24')
    UNION ALL
    SELECT 'LDIFF' FUNC, FIRST_NAME, LAST_NAME
        FROM EMPLOYEE_JOB_PERIODS
        WHERE INTERVAL(JOB_DURATION LDIFF PERIOD(DATE '2009-01-01', DATE '2010-09-24')) MONTH > 3
    UNION ALL
    SELECT 'RDIFF' FUNC, FIRST_NAME, LAST_NAME
        FROM EMPLOYEE_JOB_PERIODS
        WHERE JOB_DURATION RDIFF PERIOD(DATE '2009-01-01', DATE '2010-09-24') IS NOT NULL;