name: PR Draft Label

on:
  pull_request:
    types:
      [
        edited,
        opened,
        reopened,
        synchronize,
        converted_to_draft,
        ready_for_review,
      ]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: pr-draft-label-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_URL: ${{ github.event.pull_request.html_url }}

jobs:
  add-label-draft:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event.pull_request.draft == true
    steps:
      - name: Add label to draft PR
        run: gh pr edit "$PR_URL" --add-label "DO NOT MERGE"

  remove-label-draft:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event.pull_request.draft == false
    steps:
      - name: Remove label from PR
        run: gh pr edit "$PR_URL" --remove-label "DO NOT MERGE"
