on:
  push:
    branches:
      - main

name: Upload Release Assets

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create a GitHub release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Build DB2 Assests
        uses: vimtor/action-zip@v1
        with:
          files: DB2/
          recursive: false
          dest: db2.zip       

      - name: Build Hive Assests
        uses: vimtor/action-zip@v1
        with:
          files: Hive/
          recursive: false
          dest: hive.zip       

      - name: Build Netezza Assests
        uses: vimtor/action-zip@v1
        with:
          files: Netezza/
          recursive: false
          dest: netezza.zip       

      - name: Build Oracle Assests
        uses: vimtor/action-zip@v1
        with:
          files: Oracle/
          recursive: false
          dest: oracle.zip 

      - name: Build Redshift Assests
        uses: vimtor/action-zip@v1
        with:
          files: Redshift/
          recursive: false
          dest: redshift.zip    

      - name: Build SQL Server Assests
        uses: vimtor/action-zip@v1
        with:
          files: SQLServer/
          recursive: false
          dest: sql-server.zip    

      - name: Build Teradata Assests
        uses: vimtor/action-zip@v1
        with:
          files: Teradata/
          recursive: false
          dest: teradata.zip     

      - name: Build Vertica Assests
        uses: vimtor/action-zip@v1
        with:
          files: Vertica/
          recursive: false
          dest: vertica.zip      

      - name: Build BigQuery Assests
        uses: vimtor/action-zip@v1
        with:
          files: BigQuery/
          recursive: false
          dest: bigquery.zip

      - name: Build Databricks Assests
        uses: vimtor/action-zip@v1
        with:
          files: Databricks/
          recursive: true
          dest: databricks.zip

      - name: Build AlternativeSQLServerExtractionMethods Assests
        uses: vimtor/action-zip@v1
        with:
          files: AlternativeSQLServerExtractionMethods/
          recursive: false
          dest: AlternativeSQLServerExtractionMethods.zip

      - name: Upload DB2 Release Asset
        id: upload-db2-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./db2.zip
          asset_name: db2.zip
          asset_content_type: application/zip

      - name: Upload Hive Release Asset
        id: upload-hive-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./hive.zip
          asset_name: hive.zip
          asset_content_type: application/zip  

      - name: Upload Netezza Release Asset
        id: upload-netezza-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./netezza.zip
          asset_name: netezza.zip
          asset_content_type: application/zip  

      - name: Upload Oracle Release Asset
        id: upload-oracle-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./oracle.zip
          asset_name: oracle.zip
          asset_content_type: application/zip 

      - name: Upload Redshift Release Asset
        id: upload-redshift-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./redshift.zip
          asset_name: redshift.zip
          asset_content_type: application/zip  

      - name: Upload SQL Server Release Asset
        id: upload-sqlserver-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sql-server.zip
          asset_name: sql-server.zip
          asset_content_type: application/zip  

      - name: Upload Teradata Release Asset
        id: upload-teradata-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./teradata.zip
          asset_name: teradata.zip
          asset_content_type: application/zip  

      - name: Upload Vertica Release Asset
        id: upload-vertica-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./vertica.zip
          asset_name: vertica.zip
          asset_content_type: application/zip  

      - name: Upload BigQuery Release Asset
        id: upload-bigquery-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bigquery.zip
          asset_name: bigquery.zip
          asset_content_type: application/zip
          
      - name: Upload Databricks Release Asset
        id: upload-databricks-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./databricks.zip
          asset_name: databricks.zip
          asset_content_type: application/zip    

      - name: Upload AlternativeSQLServerExtractionMethods Assest
        id: upload-alternativeaqlserverextractionmethods-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./AlternativeSQLServerExtractionMethods.zip
          asset_name: AlternativeSQLServerExtractionMethods.zip
          asset_content_type: application/zip     
